"""Team data for the 2026 FIFA World Cup seed script.

Contains the complete 48-team roster with bilingual names, FIFA rankings,
confederation membership, and historical World Cup appearance counts.

FIFA rankings sourced from the 2025-11-19 release.  Six teams qualified
through the March 2026 play-offs and did not have a ranking at draw time;
those are recorded with ``fifa_ranking=0``.
"""

from __future__ import annotations

from typing import Any

TEAMS: list[dict[str, Any]] = [
    # ── Group A ──────────────────────────────────────────────────────────
    {
        "name": "Mexico",
        "name_zh": "墨西哥",
        "code": "MEX",
        "flag": "🇲🇽",
        "fifa_ranking": 15,
        "group_label": "A",
        "confederation": "CONCACAF",
        "world_cup_appearances": 17,
    },
    {
        "name": "South Africa",
        "name_zh": "南非",
        "code": "RSA",
        "flag": "🇿🇦",
        "fifa_ranking": 61,
        "group_label": "A",
        "confederation": "CAF",
        "world_cup_appearances": 3,
    },
    {
        "name": "South Korea",
        "name_zh": "韩国",
        "code": "KOR",
        "flag": "🇰🇷",
        "fifa_ranking": 22,
        "group_label": "A",
        "confederation": "AFC",
        "world_cup_appearances": 11,
    },
    {
        "name": "Czech Republic",
        "name_zh": "捷克",
        "code": "CZE",
        "flag": "🇨🇿",
        "fifa_ranking": 0,
        "group_label": "A",
        "confederation": "UEFA",
        "world_cup_appearances": 1,
    },
    # ── Group B ──────────────────────────────────────────────────────────
    {
        "name": "Canada",
        "name_zh": "加拿大",
        "code": "CAN",
        "flag": "🇨🇦",
        "fifa_ranking": 27,
        "group_label": "B",
        "confederation": "CONCACAF",
        "world_cup_appearances": 2,
    },
    {
        "name": "Bosnia and Herzegovina",
        "name_zh": "波黑",
        "code": "BIH",
        "flag": "🇧🇦",
        "fifa_ranking": 0,
        "group_label": "B",
        "confederation": "UEFA",
        "world_cup_appearances": 1,
    },
    {
        "name": "Qatar",
        "name_zh": "卡塔尔",
        "code": "QAT",
        "flag": "🇶🇦",
        "fifa_ranking": 51,
        "group_label": "B",
        "confederation": "AFC",
        "world_cup_appearances": 1,
    },
    {
        "name": "Switzerland",
        "name_zh": "瑞士",
        "code": "SUI",
        "flag": "🇨🇭",
        "fifa_ranking": 17,
        "group_label": "B",
        "confederation": "UEFA",
        "world_cup_appearances": 12,
    },
    # ── Group C ──────────────────────────────────────────────────────────
    {
        "name": "Brazil",
        "name_zh": "巴西",
        "code": "BRA",
        "flag": "🇧🇷",
        "fifa_ranking": 5,
        "group_label": "C",
        "confederation": "CONMEBOL",
        "world_cup_appearances": 22,
    },
    {
        "name": "Morocco",
        "name_zh": "摩洛哥",
        "code": "MAR",
        "flag": "🇲🇦",
        "fifa_ranking": 11,
        "group_label": "C",
        "confederation": "CAF",
        "world_cup_appearances": 6,
    },
    {
        "name": "Haiti",
        "name_zh": "海地",
        "code": "HAI",
        "flag": "🇭🇹",
        "fifa_ranking": 84,
        "group_label": "C",
        "confederation": "CONCACAF",
        "world_cup_appearances": 1,
    },
    {
        "name": "Scotland",
        "name_zh": "苏格兰",
        "code": "SCO",
        "flag": "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
        "fifa_ranking": 36,
        "group_label": "C",
        "confederation": "UEFA",
        "world_cup_appearances": 8,
    },
    # ── Group D ──────────────────────────────────────────────────────────
    {
        "name": "United States",
        "name_zh": "美国",
        "code": "USA",
        "flag": "🇺🇸",
        "fifa_ranking": 14,
        "group_label": "D",
        "confederation": "CONCACAF",
        "world_cup_appearances": 11,
    },
    {
        "name": "Paraguay",
        "name_zh": "巴拉圭",
        "code": "PAR",
        "flag": "🇵🇾",
        "fifa_ranking": 39,
        "group_label": "D",
        "confederation": "CONMEBOL",
        "world_cup_appearances": 10,
    },
    {
        "name": "Australia",
        "name_zh": "澳大利亚",
        "code": "AUS",
        "flag": "🇦🇺",
        "fifa_ranking": 26,
        "group_label": "D",
        "confederation": "AFC",
        "world_cup_appearances": 6,
    },
    {
        "name": "Turkey",
        "name_zh": "土耳其",
        "code": "TUR",
        "flag": "🇹🇷",
        "fifa_ranking": 0,
        "group_label": "D",
        "confederation": "UEFA",
        "world_cup_appearances": 2,
    },
    # ── Group E ──────────────────────────────────────────────────────────
    {
        "name": "Germany",
        "name_zh": "德国",
        "code": "GER",
        "flag": "🇩🇪",
        "fifa_ranking": 9,
        "group_label": "E",
        "confederation": "UEFA",
        "world_cup_appearances": 20,
    },
    {
        "name": "Curacao",
        "name_zh": "库拉索",
        "code": "CUW",
        "flag": "🇨🇼",
        "fifa_ranking": 82,
        "group_label": "E",
        "confederation": "CONCACAF",
        "world_cup_appearances": 0,
    },
    {
        "name": "Cote d’Ivoire",
        "name_zh": "科特迪瓦",
        "code": "CIV",
        "flag": "🇨🇮",
        "fifa_ranking": 42,
        "group_label": "E",
        "confederation": "CAF",
        "world_cup_appearances": 3,
    },
    {
        "name": "Ecuador",
        "name_zh": "厄瓜多尔",
        "code": "ECU",
        "flag": "🇪🇨",
        "fifa_ranking": 23,
        "group_label": "E",
        "confederation": "CONMEBOL",
        "world_cup_appearances": 4,
    },
    # ── Group F ──────────────────────────────────────────────────────────
    {
        "name": "Netherlands",
        "name_zh": "荷兰",
        "code": "NED",
        "flag": "🇳🇱",
        "fifa_ranking": 7,
        "group_label": "F",
        "confederation": "UEFA",
        "world_cup_appearances": 11,
    },
    {
        "name": "Japan",
        "name_zh": "日本",
        "code": "JPN",
        "flag": "🇯🇵",
        "fifa_ranking": 18,
        "group_label": "F",
        "confederation": "AFC",
        "world_cup_appearances": 7,
    },
    {
        "name": "Sweden",
        "name_zh": "瑞典",
        "code": "SWE",
        "flag": "🇸🇪",
        "fifa_ranking": 0,
        "group_label": "F",
        "confederation": "UEFA",
        "world_cup_appearances": 12,
    },
    {
        "name": "Tunisia",
        "name_zh": "突尼斯",
        "code": "TUN",
        "flag": "🇹🇳",
        "fifa_ranking": 40,
        "group_label": "F",
        "confederation": "CAF",
        "world_cup_appearances": 6,
    },
    # ── Group G ──────────────────────────────────────────────────────────
    {
        "name": "Belgium",
        "name_zh": "比利时",
        "code": "BEL",
        "flag": "🇧🇪",
        "fifa_ranking": 8,
        "group_label": "G",
        "confederation": "UEFA",
        "world_cup_appearances": 14,
    },
    {
        "name": "Egypt",
        "name_zh": "埃及",
        "code": "EGY",
        "flag": "🇪🇬",
        "fifa_ranking": 34,
        "group_label": "G",
        "confederation": "CAF",
        "world_cup_appearances": 3,
    },
    {
        "name": "Iran",
        "name_zh": "伊朗",
        "code": "IRN",
        "flag": "🇮🇷",
        "fifa_ranking": 20,
        "group_label": "G",
        "confederation": "AFC",
        "world_cup_appearances": 6,
    },
    {
        "name": "New Zealand",
        "name_zh": "新西兰",
        "code": "NZL",
        "flag": "🇳🇿",
        "fifa_ranking": 86,
        "group_label": "G",
        "confederation": "OFC",
        "world_cup_appearances": 2,
    },
    # ── Group H ──────────────────────────────────────────────────────────
    {
        "name": "Spain",
        "name_zh": "西班牙",
        "code": "ESP",
        "flag": "🇪🇸",
        "fifa_ranking": 1,
        "group_label": "H",
        "confederation": "UEFA",
        "world_cup_appearances": 16,
    },
    {
        "name": "Cape Verde",
        "name_zh": "佛得角",
        "code": "CPV",
        "flag": "🇨🇻",
        "fifa_ranking": 68,
        "group_label": "H",
        "confederation": "CAF",
        "world_cup_appearances": 0,
    },
    {
        "name": "Saudi Arabia",
        "name_zh": "沙特阿拉伯",
        "code": "KSA",
        "flag": "🇸🇦",
        "fifa_ranking": 60,
        "group_label": "H",
        "confederation": "AFC",
        "world_cup_appearances": 6,
    },
    {
        "name": "Uruguay",
        "name_zh": "乌拉圭",
        "code": "URU",
        "flag": "🇺🇾",
        "fifa_ranking": 16,
        "group_label": "H",
        "confederation": "CONMEBOL",
        "world_cup_appearances": 14,
    },
    # ── Group I ──────────────────────────────────────────────────────────
    {
        "name": "France",
        "name_zh": "法国",
        "code": "FRA",
        "flag": "🇫🇷",
        "fifa_ranking": 3,
        "group_label": "I",
        "confederation": "UEFA",
        "world_cup_appearances": 16,
    },
    {
        "name": "Senegal",
        "name_zh": "塞内加尔",
        "code": "SEN",
        "flag": "🇸🇳",
        "fifa_ranking": 19,
        "group_label": "I",
        "confederation": "CAF",
        "world_cup_appearances": 3,
    },
    {
        "name": "Iraq",
        "name_zh": "伊拉克",
        "code": "IRQ",
        "flag": "🇮🇶",
        "fifa_ranking": 0,
        "group_label": "I",
        "confederation": "AFC",
        "world_cup_appearances": 1,
    },
    {
        "name": "Norway",
        "name_zh": "挪威",
        "code": "NOR",
        "flag": "🇳🇴",
        "fifa_ranking": 29,
        "group_label": "I",
        "confederation": "UEFA",
        "world_cup_appearances": 3,
    },
    # ── Group J ──────────────────────────────────────────────────────────
    {
        "name": "Argentina",
        "name_zh": "阿根廷",
        "code": "ARG",
        "flag": "🇦🇷",
        "fifa_ranking": 2,
        "group_label": "J",
        "confederation": "CONMEBOL",
        "world_cup_appearances": 18,
    },
    {
        "name": "Algeria",
        "name_zh": "阿尔及利亚",
        "code": "ALG",
        "flag": "🇩🇿",
        "fifa_ranking": 35,
        "group_label": "J",
        "confederation": "CAF",
        "world_cup_appearances": 4,
    },
    {
        "name": "Austria",
        "name_zh": "奥地利",
        "code": "AUT",
        "flag": "🇦🇹",
        "fifa_ranking": 24,
        "group_label": "J",
        "confederation": "UEFA",
        "world_cup_appearances": 7,
    },
    {
        "name": "Jordan",
        "name_zh": "约旦",
        "code": "JOR",
        "flag": "🇯🇴",
        "fifa_ranking": 66,
        "group_label": "J",
        "confederation": "AFC",
        "world_cup_appearances": 0,
    },
    # ── Group K ──────────────────────────────────────────────────────────
    {
        "name": "Portugal",
        "name_zh": "葡萄牙",
        "code": "POR",
        "flag": "🇵🇹",
        "fifa_ranking": 6,
        "group_label": "K",
        "confederation": "UEFA",
        "world_cup_appearances": 8,
    },
    {
        "name": "DR Congo",
        "name_zh": "刚果民主共和国",
        "code": "COD",
        "flag": "🇨🇩",
        "fifa_ranking": 0,
        "group_label": "K",
        "confederation": "CAF",
        "world_cup_appearances": 1,
    },
    {
        "name": "Uzbekistan",
        "name_zh": "乌兹别克斯坦",
        "code": "UZB",
        "flag": "🇺🇿",
        "fifa_ranking": 50,
        "group_label": "K",
        "confederation": "AFC",
        "world_cup_appearances": 0,
    },
    {
        "name": "Colombia",
        "name_zh": "哥伦比亚",
        "code": "COL",
        "flag": "🇨🇴",
        "fifa_ranking": 13,
        "group_label": "K",
        "confederation": "CONMEBOL",
        "world_cup_appearances": 6,
    },
    # ── Group L ──────────────────────────────────────────────────────────
    {
        "name": "England",
        "name_zh": "英格兰",
        "code": "ENG",
        "flag": "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
        "fifa_ranking": 4,
        "group_label": "L",
        "confederation": "UEFA",
        "world_cup_appearances": 16,
    },
    {
        "name": "Croatia",
        "name_zh": "克罗地亚",
        "code": "CRO",
        "flag": "🇭🇷",
        "fifa_ranking": 10,
        "group_label": "L",
        "confederation": "UEFA",
        "world_cup_appearances": 6,
    },
    {
        "name": "Ghana",
        "name_zh": "加纳",
        "code": "GHA",
        "flag": "🇬🇭",
        "fifa_ranking": 72,
        "group_label": "L",
        "confederation": "CAF",
        "world_cup_appearances": 4,
    },
    {
        "name": "Panama",
        "name_zh": "巴拿马",
        "code": "PAN",
        "flag": "🇵🇦",
        "fifa_ranking": 30,
        "group_label": "L",
        "confederation": "CONCACAF",
        "world_cup_appearances": 1,
    },
]
