"""Venue data for the 2026 FIFA World Cup seed script.

Contains the complete 16-stadium roster with city, country, IANA timezone,
standard UTC offset, and seating capacity.

All 16 venues are spread across three host nations:
- United States (11 stadiums)
- Canada (2 stadiums)
- Mexico (3 stadiums)
"""

from __future__ import annotations

from typing import Any

VENUES: list[dict[str, Any]] = [
    # ── United States (11 venues) ────────────────────────────────────────
    {
        "name": "MetLife Stadium",
        "name_zh": "大都会人寿体育场",
        "city": "East Rutherford",
        "city_zh": "东拉瑟福德",
        "country": "United States",
        "country_zh": "美国",
        "timezone": "America/New_York",
        "utc_offset": "-05:00",
        "capacity": 87000,
    },
    {
        "name": "AT&T Stadium",
        "name_zh": "AT&T体育场",
        "city": "Arlington",
        "city_zh": "阿灵顿",
        "country": "United States",
        "country_zh": "美国",
        "timezone": "America/Chicago",
        "utc_offset": "-06:00",
        "capacity": 80000,
    },
    {
        "name": "SoFi Stadium",
        "name_zh": "SoFi体育场",
        "city": "Inglewood",
        "city_zh": "英格尔伍德",
        "country": "United States",
        "country_zh": "美国",
        "timezone": "America/Los_Angeles",
        "utc_offset": "-08:00",
        "capacity": 70000,
    },
    {
        "name": "Hard Rock Stadium",
        "name_zh": "硬石体育场",
        "city": "Miami Gardens",
        "city_zh": "迈阿密花园",
        "country": "United States",
        "country_zh": "美国",
        "timezone": "America/New_York",
        "utc_offset": "-05:00",
        "capacity": 65000,
    },
    {
        "name": "Mercedes-Benz Stadium",
        "name_zh": "梅赛德斯-奔驰体育场",
        "city": "Atlanta",
        "city_zh": "亚特兰大",
        "country": "United States",
        "country_zh": "美国",
        "timezone": "America/New_York",
        "utc_offset": "-05:00",
        "capacity": 71000,
    },
    {
        "name": "Lincoln Financial Field",
        "name_zh": "林肯金融球场",
        "city": "Philadelphia",
        "city_zh": "费城",
        "country": "United States",
        "country_zh": "美国",
        "timezone": "America/New_York",
        "utc_offset": "-05:00",
        "capacity": 69000,
    },
    {
        "name": "Lumen Field",
        "name_zh": "流明球场",
        "city": "Seattle",
        "city_zh": "西雅图",
        "country": "United States",
        "country_zh": "美国",
        "timezone": "America/Los_Angeles",
        "utc_offset": "-08:00",
        "capacity": 69000,
    },
    {
        "name": "Gillette Stadium",
        "name_zh": "吉列体育场",
        "city": "Foxborough",
        "city_zh": "福克斯堡",
        "country": "United States",
        "country_zh": "美国",
        "timezone": "America/New_York",
        "utc_offset": "-05:00",
        "capacity": 65000,
    },
    {
        "name": "NRG Stadium",
        "name_zh": "NRG体育场",
        "city": "Houston",
        "city_zh": "休斯顿",
        "country": "United States",
        "country_zh": "美国",
        "timezone": "America/Chicago",
        "utc_offset": "-06:00",
        "capacity": 72000,
    },
    {
        "name": "Arrowhead Stadium",
        "name_zh": "箭头体育场",
        "city": "Kansas City",
        "city_zh": "堪萨斯城",
        "country": "United States",
        "country_zh": "美国",
        "timezone": "America/Chicago",
        "utc_offset": "-06:00",
        "capacity": 76000,
    },
    {
        "name": "Levi's Stadium",
        "name_zh": "李维斯体育场",
        "city": "Santa Clara",
        "city_zh": "圣克拉拉",
        "country": "United States",
        "country_zh": "美国",
        "timezone": "America/Los_Angeles",
        "utc_offset": "-08:00",
        "capacity": 68000,
    },
    # ── Canada (2 venues) ────────────────────────────────────────────────
    {
        "name": "BMO Field",
        "name_zh": "BMO球场",
        "city": "Toronto",
        "city_zh": "多伦多",
        "country": "Canada",
        "country_zh": "加拿大",
        "timezone": "America/Toronto",
        "utc_offset": "-05:00",
        "capacity": 45000,
    },
    {
        "name": "BC Place",
        "name_zh": "BC体育馆",
        "city": "Vancouver",
        "city_zh": "温哥华",
        "country": "Canada",
        "country_zh": "加拿大",
        "timezone": "America/Vancouver",
        "utc_offset": "-08:00",
        "capacity": 54000,
    },
    # ── Mexico (3 venues) ────────────────────────────────────────────────
    {
        "name": "Estadio Azteca",
        "name_zh": "阿兹特克体育场",
        "city": "Mexico City",
        "city_zh": "墨西哥城",
        "country": "Mexico",
        "country_zh": "墨西哥",
        "timezone": "America/Mexico_City",
        "utc_offset": "-06:00",
        "capacity": 87000,
    },
    {
        "name": "Estadio BBVA",
        "name_zh": "BBVA体育场",
        "city": "Monterrey",
        "city_zh": "蒙特雷",
        "country": "Mexico",
        "country_zh": "墨西哥",
        "timezone": "America/Monterrey",
        "utc_offset": "-06:00",
        "capacity": 53000,
    },
    {
        "name": "Estadio Akron",
        "name_zh": "阿克伦体育场",
        "city": "Guadalajara",
        "city_zh": "瓜达拉哈拉",
        "country": "Mexico",
        "country_zh": "墨西哥",
        "timezone": "America/Mexico_City",
        "utc_offset": "-06:00",
        "capacity": 49000,
    },
]